### ISSUE TITLE
Update main page

### ISSUE THREAD

**Issue by Ethan-ZYF** [XFTTech/UTLeetcoder#21]
- [x] 两个图表
<del>- [ ] 左边一个折线图，全站提交总量变化</del>
- [x] 左边一个rank，每个人刷题总量，显示前十，前三做UI优化，效果图参考：
- [x] 右边一个rank，每个人rating，显示前十，前三做UI优化，效果图参考：
<img width="407" alt="image" src="https://user-images.githubusercontent.com/90292101/213307343-9b11513b-946b-4fb9-931c-4821516fdf01.png">

**Comment by Yorafa** [comment]
How about the daily submission change? If we do line graph on whole site seems too monotone.

**Comment by Ethan-ZYF** [comment]
> How about the daily submission change? If we do line graph on whole site seems too monotone.

or maybe line chart for each user. each user owns a line.

**Comment by Yorafa** [comment]
> > How about the daily submission change? If we do line graph on whole site seems too monotone.
> 
> or maybe line chart for each user. each user owns a line.

Cool idea, too crowd to display all users' line when large amount of users exist? Personal idea is to use selected users' line instead, i.e. highest and lowest (with submission)

**Comment by Ethan-ZYF** [comment]
> > > How about the daily submission change? If we do line graph on whole site seems too monotone.
> > 
> > 
> > or maybe line chart for each user. each user owns a line.
> 
> Cool idea, too crowd to display all users' line when large amount of users exist? Personal idea is to use selected users' line instead, i.e. highest and lowest (with submission)

或者简单点，两个榜，一个周赛分的榜，一个总题数的榜，前三名还是做UI优化，这样我们也好做

**Comment by Yorafa** [comment]
- [ ] mobile responsive
